In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving adult.csv to adult.csv

In [ ]:
df = pd.read_csv('adult.csv')

In [ ]:
df.head

<bound method NDFrame.head of        age workclass  fnlwgt     education  education.num      marital.status  \
0       90         ?   77053       HS-grad              9             Widowed
1       82   Private  132870       HS-grad              9             Widowed
2       66         ?  186061  Some-college             10             Widowed
3       54   Private  140359       7th-8th              4            Divorced
4       41   Private  264663  Some-college             10           Separated
...    ...       ...     ...           ...            ...                 ...
32556   22   Private  310152  Some-college             10       Never-married
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse
32558   40   Private  154374       HS-grad              9  Married-civ-spouse
32559   58   Private  151910       HS-grad              9             Widowed
32560   22   Private  201490       HS-grad              9       Never-married

              occupation   relationship   race     sex  capital.gain  \
0                      ?  Not-in-family  White  Female             0
1        Exec-managerial  Not-in-family  White  Female             0
2                      ?      Unmarried  Black  Female             0
3      Machine-op-inspct      Unmarried  White  Female             0
4         Prof-specialty      Own-child  White  Female             0
...                  ...            ...    ...     ...           ...
32556    Protective-serv  Not-in-family  White    Male             0
32557       Tech-support           Wife  White  Female             0
32558  Machine-op-inspct        Husband  White    Male             0
32559       Adm-clerical      Unmarried  White  Female             0
32560       Adm-clerical      Own-child  White    Male             0

       capital.loss  hours.per.week native.country income
0              4356              40  United-States  <=50K
1              4356              18  United-States  <=50K
2              4356              40  United-States  <=50K
3              3900              40  United-States  <=50K
4              3900              40  United-States  <=50K
...             ...             ...            ...    ...
32556             0              40  United-States  <=50K
32557             0              38  United-States  <=50K
32558             0              40  United-States   >50K
32559             0              40  United-States  <=50K
32560             0              20  United-States  <=50K

[32561 rows x 15 columns]>

In [ ]:
df.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [ ]:
df.describe()

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [ ]:
df = df.replace('?', np.nan)

print("Missing values after '?' replacement:")
display(df.isnull().sum())

Missing values after '?' replacement:

age                  0
workclass         1836
fnlwgt               0
education            0
education.num        0
marital.status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital.gain         0
capital.loss         0
hours.per.week       0
native.country     583
income               0
dtype: int64

In [ ]:
df = df.drop(columns=['fnlwgt', 'capital.gain', 'capital.loss'])
print("DataFrame after dropping 'fnlwgt', 'capital.gain', 'capital.loss':")
display(df.head())

DataFrame after dropping 'fnlwgt', 'capital.gain', 'capital.loss':

,age,workclass,education,education.num,marital.status,occupation,relationship,race,sex,hours.per.week,native.country,income
0,90,NaN,HS-grad,9,Widowed,NaN,Not-in-family,White,Female,40,United-States,<=50K
1,82,Private,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,18,United-States,<=50K
2,66,NaN,Some-college,10,Widowed,NaN,Unmarried,Black,Female,40,United-States,<=50K
3,54,Private,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,40,United-States,<=50K
4,41,Private,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,40,United-States,<=50K

In [ ]:
# Create age groups
df['age_group'] = pd.cut(df['age'], bins=[0, 25, 45, 65, np.inf], labels=['Young', 'Adult', 'Senior', 'Elderly'])

# Create hours per week groups
df['hours_per_week_group'] = pd.cut(df['hours.per.week'], bins=[0, 30, 40, 50, np.inf], labels=['Part-time', 'Full-time', 'Over-time', 'Very-long'])

# Impute missing values in original categorical columns with their mode
for col in ['workclass', 'occupation', 'native.country']:
    if col in df.columns and df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mode()[0])

print("DataFrame with new features 'age_group' and 'hours_per_week_group' and imputed NaNs:")
display(df.head())

# Convert 'age_group' and 'hours_per_week_group' to 'object' dtype so they are picked up by get_dummies later
df['age_group'] = df['age_group'].astype('object')
df['hours_per_week_group'] = df['hours_per_week_group'].astype('object')

DataFrame with new features 'age_group' and 'hours_per_week_group' and imputed NaNs:

,age,education.num,hours.per.week,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Without-pay,...,native.country_Yugoslavia,income_>50K,age_group_Elderly,age_group_Senior,age_group_Young,hours_per_week_group_Over-time,hours_per_week_group_Part-time,hours_per_week_group_Very-long,age_group,hours_per_week_group
0,90,9,40,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,Elderly,Full-time
1,82,9,18,False,False,True,False,False,False,False,...,False,False,True,False,False,False,True,False,Elderly,Part-time
2,66,10,40,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,Elderly,Full-time
3,54,4,40,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,Senior,Full-time
4,41,10,40,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,Adult,Full-time

In [ ]:
import numpy as np
import pandas as pd

# Define target column names
target_raw_col_name = 'income'
target_encoded_col_name = 'income_>50K'

# Create a fresh copy of the DataFrame to ensure clean processing
df_temp = df.copy()

# --- Step 1: Clean up duplicate columns first if any exist from previous partial runs ---
# This ensures that when we select_dtypes, we are not confused by duplicate names.
df_temp = df_temp.loc[:, ~df_temp.columns.duplicated()]

# --- Step 2: Process the target column ---
# If income_>50K doesn't exist, create it from 'income'
if target_encoded_col_name not in df_temp.columns:
    if target_raw_col_name in df_temp.columns:
        df_temp[target_encoded_col_name] = (df_temp[target_raw_col_name] == ' >50K').astype(int)
        df_temp = df_temp.drop(columns=[target_raw_col_name])
        print(f"Encoded '{target_raw_col_name}' into '{target_encoded_col_name}' (0/1) and dropped original.")
    else:
        raise ValueError("Neither 'income' nor 'income_>50K' found in DataFrame. Cannot define target.")
else:
    df_temp[target_encoded_col_name] = df_temp[target_encoded_col_name].astype(int)
    if target_raw_col_name in df_temp.columns:
        df_temp = df_temp.drop(columns=[target_raw_col_name])
    print(f"Target column '{target_encoded_col_name}' already exists and is ensured to be integer (0/1).")

# Separate target from features
y = df_temp[target_encoded_col_name]
X = df_temp.drop(columns=[target_encoded_col_name])

# --- Step 3: Process features (X) for one-hot encoding ---
categorical_cols_to_encode = X.select_dtypes(include=['object', 'category']).columns.tolist()

if categorical_cols_to_encode:
    print(f"Performing one-hot encoding on categorical feature columns: {categorical_cols_to_encode}")
    X_encoded_part = pd.get_dummies(X[categorical_cols_to_encode], drop_first=True)
    X_numerical_part = X.drop(columns=categorical_cols_to_encode)

    for col in X_encoded_part.columns:
        if X_encoded_part[col].dtype == 'bool':
            X_encoded_part[col] = X_encoded_part[col].astype(int)

    X_processed = pd.concat([X_numerical_part.reset_index(drop=True), X_encoded_part.reset_index(drop=True)], axis=1)
else:
    print("No object or category feature columns found for one-hot encoding. All features appear to be numerical or boolean.")
    X_processed = X.copy() # All features are already numerical or boolean

# --- Step 4: Final cleanup of feature columns ---
# Convert any remaining boolean feature columns to integers
for col in X_processed.columns:
    if X_processed[col].dtype == 'bool':
        X_processed[col] = X_processed[col].astype(int)

# Reconstruct the DataFrame with the fully processed features and target
df = pd.concat([X_processed.reset_index(drop=True), y.reset_index(drop=True)], axis=1)

print("Final DataFrame state after comprehensive preprocessing:")
display(df.head())
print(f"Shape of df: {df.shape}")
print(f"Columns of df: {df.columns.tolist()}")

Target column 'income_>50K' already exists and is ensured to be integer (0/1).
No object or category feature columns found for one-hot encoding. All features appear to be numerical or boolean.
Final DataFrame state after comprehensive preprocessing:

,age,education.num,hours.per.week,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Without-pay,...,native.country_United-States,native.country_Vietnam,native.country_Yugoslavia,age_group_Elderly,age_group_Senior,age_group_Young,hours_per_week_group_Over-time,hours_per_week_group_Part-time,hours_per_week_group_Very-long,income_>50K
0,90,9,40,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
1,82,9,18,0,0,1,0,0,0,0,...,1,0,0,1,0,0,0,1,0,0
2,66,10,40,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
3,54,4,40,0,0,1,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
4,41,10,40,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

Shape of df: (32561, 101)
Columns of df: ['age', 'education.num', 'hours.per.week', 'workclass_Local-gov', 'workclass_Never-worked', 'workclass_Private', 'workclass_Self-emp-inc', 'workclass_Self-emp-not-inc', 'workclass_State-gov', 'workclass_Without-pay', 'education_11th', 'education_12th', 'education_1st-4th', 'education_5th-6th', 'education_7th-8th', 'education_9th', 'education_Assoc-acdm', 'education_Assoc-voc', 'education_Bachelors', 'education_Doctorate', 'education_HS-grad', 'education_Masters', 'education_Preschool', 'education_Prof-school', 'education_Some-college', 'marital.status_Married-AF-spouse', 'marital.status_Married-civ-spouse', 'marital.status_Married-spouse-absent', 'marital.status_Never-married', 'marital.status_Separated', 'marital.status_Widowed', 'occupation_Armed-Forces', 'occupation_Craft-repair', 'occupation_Exec-managerial', 'occupation_Farming-fishing', 'occupation_Handlers-cleaners', 'occupation_Machine-op-inspct', 'occupation_Other-service', 'occupation_Priv-house-serv', 'occupation_Prof-specialty', 'occupation_Protective-serv', 'occupation_Sales', 'occupation_Tech-support', 'occupation_Transport-moving', 'relationship_Not-in-family', 'relationship_Other-relative', 'relationship_Own-child', 'relationship_Unmarried', 'relationship_Wife', 'race_Asian-Pac-Islander', 'race_Black', 'race_Other', 'race_White', 'sex_Male', 'native.country_Canada', 'native.country_China', 'native.country_Columbia', 'native.country_Cuba', 'native.country_Dominican-Republic', 'native.country_Ecuador', 'native.country_El-Salvador', 'native.country_England', 'native.country_France', 'native.country_Germany', 'native.country_Greece', 'native.country_Guatemala', 'native.country_Haiti', 'native.country_Holand-Netherlands', 'native.country_Honduras', 'native.country_Hong', 'native.country_Hungary', 'native.country_India', 'native.country_Iran', 'native.country_Ireland', 'native.country_Italy', 'native.country_Jamaica', 'native.country_Japan', 'native.country_Laos', 'native.country_Mexico', 'native.country_Nicaragua', 'native.country_Outlying-US(Guam-USVI-etc)', 'native.country_Peru', 'native.country_Philippines', 'native.country_Poland', 'native.country_Portugal', 'native.country_Puerto-Rico', 'native.country_Scotland', 'native.country_South', 'native.country_Taiwan', 'native.country_Thailand', 'native.country_Trinadad&Tobago', 'native.country_United-States', 'native.country_Vietnam', 'native.country_Yugoslavia', 'age_group_Elderly', 'age_group_Senior', 'age_group_Young', 'hours_per_week_group_Over-time', 'hours_per_week_group_Part-time', 'hours_per_week_group_Very-long', 'income_>50K']

In [ ]:
print('Displaying head of DataFrame after fixed preprocessing:')
display(df.head())

Displaying head of DataFrame after fixed preprocessing:

,age,education.num,hours.per.week,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Without-pay,...,native.country_United-States,native.country_Vietnam,native.country_Yugoslavia,age_group_Elderly,age_group_Senior,age_group_Young,hours_per_week_group_Over-time,hours_per_week_group_Part-time,hours_per_week_group_Very-long,income_>50K
0,90,9,40,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
1,82,9,18,0,0,1,0,0,0,0,...,1,0,0,1,0,0,0,1,0,0
2,66,10,40,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
3,54,4,40,0,0,1,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
4,41,10,40,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
print('Displaying head of DataFrame after fixed preprocessing:')
display(df.head())

Displaying head of DataFrame after fixed preprocessing:

,age,education.num,hours.per.week,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Without-pay,...,native.country_United-States,native.country_Vietnam,native.country_Yugoslavia,age_group_Elderly,age_group_Senior,age_group_Young,hours_per_week_group_Over-time,hours_per_week_group_Part-time,hours_per_week_group_Very-long,income_>50K
0,90,9,40,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
1,82,9,18,0,0,1,0,0,0,0,...,1,0,0,1,0,0,0,1,0,0
2,66,10,40,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
3,54,4,40,0,0,1,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
4,41,10,40,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
print('Displaying head of DataFrame after fixed preprocessing:')
display(df.head())

Displaying head of DataFrame after fixed preprocessing:

,age,education.num,hours.per.week,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Without-pay,...,native.country_United-States,native.country_Vietnam,native.country_Yugoslavia,age_group_Elderly,age_group_Senior,age_group_Young,hours_per_week_group_Over-time,hours_per_week_group_Part-time,hours_per_week_group_Very-long,income_>50K
0,90,9,40,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
1,82,9,18,0,0,1,0,0,0,0,...,1,0,0,1,0,0,0,1,0,0
2,66,10,40,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
3,54,4,40,0,0,1,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
4,41,10,40,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
print('Displaying head of DataFrame after fixed preprocessing:')
display(df.head())

Displaying head of DataFrame after fixed preprocessing:

,age,education.num,hours.per.week,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Without-pay,...,native.country_United-States,native.country_Vietnam,native.country_Yugoslavia,age_group_Elderly,age_group_Senior,age_group_Young,hours_per_week_group_Over-time,hours_per_week_group_Part-time,hours_per_week_group_Very-long,income_>50K
0,90,9,40,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
1,82,9,18,0,0,1,0,0,0,0,...,1,0,0,1,0,0,0,1,0,0
2,66,10,40,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
3,54,4,40,0,0,1,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
4,41,10,40,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
print('Displaying head of DataFrame after fixed preprocessing:')
display(df.head())

Displaying head of DataFrame after fixed preprocessing:

,age,education.num,hours.per.week,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Without-pay,...,native.country_United-States,native.country_Vietnam,native.country_Yugoslavia,age_group_Elderly,age_group_Senior,age_group_Young,hours_per_week_group_Over-time,hours_per_week_group_Part-time,hours_per_week_group_Very-long,income_>50K
0,90,9,40,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
1,82,9,18,0,0,1,0,0,0,0,...,1,0,0,1,0,0,0,1,0,0
2,66,10,40,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
3,54,4,40,0,0,1,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
4,41,10,40,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
print('Displaying head of DataFrame after fixed preprocessing:')
display(df.head())

Displaying head of DataFrame after fixed preprocessing:

,age,education.num,hours.per.week,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Without-pay,...,age_group_Young,hours_per_week_group_Over-time,hours_per_week_group_Part-time,hours_per_week_group_Very-long,age_group_Elderly,age_group_Senior,age_group_Young,hours_per_week_group_Over-time,hours_per_week_group_Part-time,hours_per_week_group_Very-long
0,90,9,40,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
1,82,9,18,False,False,True,False,False,False,False,...,False,False,True,False,True,False,False,False,True,False
2,66,10,40,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,54,4,40,False,False,True,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4,41,10,40,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.head()

,age,education.num,hours.per.week,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Without-pay,...,age_group_Young,hours_per_week_group_Over-time,hours_per_week_group_Part-time,hours_per_week_group_Very-long,age_group_Elderly,age_group_Senior,age_group_Young,hours_per_week_group_Over-time,hours_per_week_group_Part-time,hours_per_week_group_Very-long
0,90,9,40,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
1,82,9,18,False,False,True,False,False,False,False,...,False,False,True,False,True,False,False,False,True,False
2,66,10,40,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,54,4,40,False,False,True,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4,41,10,40,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

X = df.drop('income_>50K', axis=1)
y = df['income_>50K']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Data split into training and testing sets (re-run after preprocessing fix):")
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")

Data split into training and testing sets (re-run after preprocessing fix):
X_train shape: (26048, 106)
y_train shape: (26048,)
X_test shape: (6513, 106)
y_test shape: (6513,)

In [ ]:
base_estimator = DecisionTreeClassifier(max_depth=1, random_state=42)

adaboost_model = AdaBoostClassifier(estimator=base_estimator, n_estimators=100, random_state=42)

adaboost_model.fit(X_train, y_train)

print("AdaBoost model trained successfully.")

AdaBoost model trained successfully.

In [ ]:
y_pred = adaboost_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"AdaBoost Model Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(report)

AdaBoost Model Accuracy: 0.8257

Classification Report:
              precision    recall  f1-score   support

       False       0.86      0.93      0.89      4976
        True       0.68      0.50      0.58      1537

    accuracy                           0.83      6513
   macro avg       0.77      0.71      0.73      6513
weighted avg       0.81      0.83      0.82      6513

In [ ]:
from catboost import CatBoostClassifier

catboost_model = CatBoostClassifier(iterations=100,
                                    learning_rate=0.1,
                                    depth=6,
                                    loss_function='Logloss',
                                    random_seed=42,
                                    verbose=False)

In [ ]:
print('Training CatBoost model...')
catboost_model.fit(X_train, y_train)
print("CatBoost model trained successfully.")

Training CatBoost model...
CatBoost model trained successfully.

In [ ]:
y_pred_catboost = catboost_model.predict(X_test)

accuracy_catboost = accuracy_score(y_test, y_pred_catboost)
report_catboost = classification_report(y_test, y_pred_catboost)

print(f"CatBoost Model Accuracy: {accuracy_catboost:.4f}")
print("\nCatBoost Classification Report:")
print(report_catboost)

CatBoost Model Accuracy: 0.8388

CatBoost Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.93      0.90      4976
           1       0.70      0.55      0.62      1537

    accuracy                           0.84      6513
   macro avg       0.79      0.74      0.76      6513
weighted avg       0.83      0.84      0.83      6513